### ISSUE TITLE
Buildah Network Issue

### ISSUE THREAD

**Issue by Fosol** [bcgov/pipeline-templates#21]
My Buildah Task can't fetch packages when building an image from a Dockerfile.

Is there a Network Policy that needs to be applied?

```
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
```

**Comment by gregnrobinson** [comment]
Based on issue #22 has the network connectivity been resolved? If so, can you comment on what the issue was for visibility?

**Comment by Fosol** [comment]
I don't know what the issue was regrettably.  I'll try your other branch and test again and add feedback here.

It worked one time...  Which had nothing to do with my changes, just random luck.  I could pull those same packages by building the image with a BuildConfig instead of Buildah.
