### ISSUE TITLE
Buildah Not Authenticated to Pull Images from RedHat

### ISSUE THREAD

**Issue by Fosol** [bcgov/pipeline-templates#22]
Regrettably Buildah doesn't have the right authentication to pull images from RedHat, which makes it pretty difficult to use in Openshift.

```
+ buildah --storage-driver=vfs bud --format=oci --tls-verify=true --no-cache -f Dockerfile.buildah -t tno-app-editor:latest .
STEP 1: FROM ubi8/nodejs-16 AS build-deps
error creating build container: The following failures happened while trying to pull image specified by "ubi8/nodejs-16" based on search registries in /etc/containers/registries.conf:
* "localhost/ubi8/nodejs-16": Error initializing source docker://localhost/ubi8/nodejs-16:latest: error pinging docker registry localhost: Get "https://localhost/v2/": dial tcp [::1]:443: connect: connection refused
* "registry.access.redhat.com/ubi8/nodejs-16": Error initializing source docker://registry.access.redhat.com/ubi8/nodejs-16:latest: error pinging docker registry registry.access.redhat.com: invalid status code from registry 504 (Gateway Timeout)
* "registry.redhat.io/ubi8/nodejs-16": Error initializing source docker://registry.redhat.io/ubi8/nodejs-16:latest: unable to retrieve auth token: invalid username/password: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
* "docker.io/ubi8/nodejs-16": Error initializing source docker://ubi8/nodejs-16:latest: Error reading manifest latest in docker.io/ubi8/nodejs-16: errors:
denied: requested access to the resource is denied
unauthorized: authentication required
```

**Comment by gregnrobinson** [comment]
Hey there @Fosol I currently have a [PR](https://github.com/bcgov/pipeline-templates/tree/buildah-image-registry-refactoring) that aims to help resolve authentication for image registries. Can you confirm if you executed the build task for that branch? if so, I can investigate adding support if possible. We may have add additional build technologies if it won't be possible.

**Comment by gregnrobinson** [comment]
based on the output it appears you may have pulled from main.

**Comment by Fosol** [comment]
Yes I would have used the default branch.  I'll test with your other branch and hope things work.

**Comment by gregnrobinson** [comment]
Just to confirm using the latest build and push PipelineRun, modifying the image registry to `registry.redhat.io` and setting the `image-registry-username` and `image-registry-password` does not authenticate properly? I have not used red hats image registry so just trying to understand where it is breaking specifically.

**Comment by Fosol** [comment]
We don't have a username and password to connect to redhat registry.  Openshift has been setup with authorization to enable pulling images.  Locally we can't pull rhel images from redhat registry.  Not sure how we enable Buildah to have the same permissions that native BuildConfig and DeployConfig objects have.

**Comment by gregnrobinson** [comment]
Ah ok, I understand now. I will investigate this possibility.

**Comment by w8896699** [comment]
Hi @Fosol is this issue still block you? Each project set tools namespace has a Secret called `platform-services-controlled-etc-pki-entitlement` which can be used to pull non-public from Red Hat repositories.

**Comment by Fosol** [comment]
I simply don't bother using images from Red Hat.  But if I need to I'll look into that secret and see if I can get Buildah to use it.

**Comment by w8896699** [comment]
I have tested it both locally and one openshift pipeline task, with that token, I am able to pull the image from red hat image repositories. I will close this issue for now.
