### ISSUE TITLE
Testing Pipeline Failing on Sonar Scan

### ISSUE THREAD

**Issue by gregnrobinson** [bcgov/pipeline-templates#34]
Hey folks, looks like you need to update the sonar project for the sonar scan testing GitHub workflow. This pipeline runs every Sunday and I get emails when it fails. Should be an easy fix. Just need a sonar project that you want to use for testing.

```
Error:  Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default-cli) on project maven-test: Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator -> [Help 1]
Error: 
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error: 
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error: Process completed with exit code 1.
```

**Comment by gregnrobinson** [comment]
Hey @mitovskaol this still needs to be addressed...

Just requires your team to edit the [pom.xml](https://github.com/bcgov/pipeline-templates/blob/main/tekton/demo/maven-test/pom.xml) in the demo folder with a maven project that exists. 

This is causing the testing workflow to fail every week...

**Comment by mitovskaol** [comment]
@ShellyXueHan @caggles  Is this something that one of you can do ?

**Comment by w8896699** [comment]
Close, fixing on https://github.com/bcgov/pipeline-templates/pull/60 and https://github.com/bcgov/pipeline-templates/pull/57
